### ISSUE TITLE
NotFoundError: NotFoundError: DOM Exception 8

### ISSUE THREAD

**Issue by rianby64** [m3co/tree3#19]
https://sentry.io/3-constructora-sas/tree3/issues/183953601/

```
NotFoundError: NotFoundError: DOM Exception 8
  at HTMLLIElement.removeLeaf (/tree3.js:193:10)
  at HTMLInputElement.<anonymous> (/tree3.js:119:14)
```

**Comment by rianby64** [comment]
Abandoned...
