### ISSUE TITLE
TypeError: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by rianby64** [m3co/tree3#29]
https://sentry.io/3-constructora-sas/tree3/issues/187817178/

```
TypeError: Object doesn't support property or method 'includes'
  at createContextmenu (/tree3.js:230:13)
  at appendLeaf (/tree3.js:67:5)
  at Anonymous function (/tree3.js:386:7)
```

**Comment by rianby64** [comment]
Move this polyfill to a single repo...
