### ISSUE TITLE
TypeError: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by rianby64** [m3co/tree3#45]
https://sentry.io/3-constructora-sas/tree3/issues/202153067/

```
TypeError: Unable to get property 'length' of undefined or null reference
  at p (/docs/scripts/docstrap.lib.js:3:22927)
  at a.Sunlight.registerLanguage (/docs/scripts/docstrap.lib.js:4:618)
  at Anonymous function (/docs/scripts/docstrap.lib.js:4:1540)
  at Global code (/docs/scripts/docstrap.lib.js:1:1)
```

**Comment by rianby64** [comment]
Abandoned...
