### ISSUE TITLE
TypeError: Unable to get property 'contextItems' of undefined or null reference

### ISSUE THREAD

**Issue by rianby64** [m3co/tree3#46]
https://sentry.io/3-constructora-sas/tree3/issues/202153068/

```
TypeError: Unable to get property 'contextItems' of undefined or null reference
  at l (/docs/scripts/docstrap.lib.js:3:26419)
  at o (/docs/scripts/docstrap.lib.js:3:28106)
  at a (/docs/scripts/docstrap.lib.js:3:31267)
  at a.Sunlight.highlightAll (/docs/scripts/docstrap.lib.js:4:320)
  at Anonymous function (/docs/tutorial-simpleTree.html:268:2)
...
(5 additional frame(s) were not displayed)
```

**Comment by rianby64** [comment]
Abandoned...
